Repository seisbench/seisbench, pull requests merged in 2025-05, with the labels that each got.

#348 Fix handling of fractional offsets in annotation
  seisbench/models/base.py
  tests/test_models.py
Labels: enhancement

#350 rearrange: performance improvements
  seisbench/models/base.py
  tests/test_models.py
Labels: enhancement

#351 Add warning about label columns to PickLabeller (Closes #335)
  seisbench/generate/labeling.py
  tests/test_generate.py
Labels: documentation, enhancement

#352 Fix 404 handling in list_pretrained (Closes #174)
  seisbench/models/base.py
  tests/test_models.py
Labels: enhancement

#355 skynet integration
  contrib/model_conversion/skynet_seisbench_integration.ipynb
  docs/pages/documentation/models.rst
  docs/pages/models.rst
  seisbench/models/__init__.py
  seisbench/models/skynet.py
  tests/models/test_skynet.py
Labels: model extension

#357 Enable specifying overlaps in annotate as fractions instead (Closes #353)
  seisbench/models/base.py
  seisbench/models/phasenet.py
  tests/test_models.py
Labels: enhancement
