Repository seisbench/seisbench, pull requests merged in 2025-08, with the labels that each got.

#360 Training an own Denoiser model
  README.md
  docs/pages/documentation/models.rst
  docs/pages/examples.rst
  docs/pages/models.rst
  examples/03e_training_denoiser.ipynb
  examples/README.md
  seisbench/generate/__init__.py
  seisbench/generate/labeling.py
  seisbench/models/__init__.py
  seisbench/models/base.py
  seisbench/models/deepdenoiser.py
  seisbench/models/seisdae.py
  seisbench/util/torch_helpers.py
  tests/test_generate.py
  tests/test_models.py
Labels: model extension

#362 Add to_preferred_device function
  examples/01b_model_api.ipynb
  examples/02a_deploy_model_on_streams_example.ipynb
  examples/02b_deep_denoiser.ipynb
  examples/02c_depth_phases.ipynb
  examples/03a_training_phasenet.ipynb
  examples/03c_catalog_seisbench_gamma.ipynb
  examples/03d_catalog_seisbench_pyocto.ipynb
  seisbench/models/base.py
Labels: enhancement

#371 DOC: Fix a few typos in documentation page "The SeisBench data format"
  docs/pages/data_format.rst
Labels: documentation

#372 [bugfix] Labelling for denoised channels was not set
  seisbench/models/seisdae.py
Labels: bug
